GET http://localhost:4004/catalog/Authors
###
GET http://localhost:4004/catalog/Authors?$expand=books

###
GET http://localhost:4004/catalog/Books
###

GET http://localhost:4004/catalog/Books?$expand=orders
###
GET http://localhost:4004/catalog/Books?$expand=author

###
GET http://localhost:4004/catalog/Orders

###
GET http://localhost:4004/catalog/Orders?$expand=book
###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{
    "ID": 5,
    "title": "Oil & Gas",
    "stock": 21,
    "author_ID": 203

}

###
POST http://localhost:4004/catalog/Orders
Content-Type: application/json

{
    "book_ID" : 3,
    "quantity" : 1
}

