GET http://localhost:4004/catalog/Authors

###
GET http://localhost:4004/catalog/Books

###
GET http://localhost:4004/catalog/Orders
###
POST http://localhost:4004/catalog/Books
Content-Type: application/json

{
    "ID": 5,
    "title": "Oil & Gas",
    "stock": 21,
    "author_ID": 501

}